"""SDTM reference metadata used by the agent's tools.

A compact subset of SDTMIG (v3.3/3.4) domain specifications and CDISC
controlled terminology. Core values: Req = required, Exp = expected,
Perm = permissible.
"""

from __future__ import annotations

# (variable, label, type, core)
_IDENTIFIERS = [
    ("STUDYID", "Study Identifier", "Char", "Req"),
    ("DOMAIN", "Domain Abbreviation", "Char", "Req"),
    ("USUBJID", "Unique Subject Identifier", "Char", "Req"),
]

_TIMING_VISIT = [
    ("VISITNUM", "Visit Number", "Num", "Exp"),
    ("VISIT", "Visit Name", "Char", "Perm"),
]

DOMAINS: dict[str, dict] = {
    "DM": {
        "label": "Demographics",
        "class": "Special-Purpose",
        "structure": "One record per subject",
        "variables": [
            ("STUDYID", "Study Identifier", "Char", "Req"),
            ("DOMAIN", "Domain Abbreviation", "Char", "Req"),
            ("USUBJID", "Unique Subject Identifier", "Char", "Req"),
            ("SUBJID", "Subject Identifier for the Study", "Char", "Req"),
            ("RFSTDTC", "Subject Reference Start Date/Time", "Char", "Exp"),
            ("RFENDTC", "Subject Reference End Date/Time", "Char", "Exp"),
            ("RFXSTDTC", "Date/Time of First Study Treatment", "Char", "Exp"),
            ("RFXENDTC", "Date/Time of Last Study Treatment", "Char", "Exp"),
            ("RFICDTC", "Date/Time of Informed Consent", "Char", "Exp"),
            ("RFPENDTC", "Date/Time of End of Participation", "Char", "Exp"),
            ("DTHDTC", "Date/Time of Death", "Char", "Exp"),
            ("DTHFL", "Subject Death Flag", "Char", "Exp"),
            ("SITEID", "Study Site Identifier", "Char", "Req"),
            ("BRTHDTC", "Date/Time of Birth", "Char", "Perm"),
            ("AGE", "Age", "Num", "Exp"),
            ("AGEU", "Age Units", "Char", "Exp"),
            ("SEX", "Sex", "Char", "Req"),
            ("RACE", "Race", "Char", "Exp"),
            ("ETHNIC", "Ethnicity", "Char", "Perm"),
            ("ARMCD", "Planned Arm Code", "Char", "Exp"),
            ("ARM", "Description of Planned Arm", "Char", "Exp"),
            ("ACTARMCD", "Actual Arm Code", "Char", "Exp"),
            ("ACTARM", "Description of Actual Arm", "Char", "Exp"),
            ("COUNTRY", "Country", "Char", "Req"),
            ("DMDTC", "Date/Time of Collection", "Char", "Perm"),
            ("DMDY", "Study Day of Collection", "Num", "Perm"),
        ],
    },
    "AE": {
        "label": "Adverse Events",
        "class": "Events",
        "structure": "One record per adverse event per subject",
        "variables": _IDENTIFIERS
        + [
            ("AESEQ", "Sequence Number", "Num", "Req"),
            ("AESPID", "Sponsor-Defined Identifier", "Char", "Perm"),
            ("AETERM", "Reported Term for the Adverse Event", "Char", "Req"),
            ("AEMODIFY", "Modified Reported Term", "Char", "Perm"),
            ("AEDECOD", "Dictionary-Derived Term", "Char", "Req"),
            ("AEBODSYS", "Body System or Organ Class", "Char", "Exp"),
            ("AESOC", "Primary System Organ Class", "Char", "Exp"),
            ("AESEV", "Severity/Intensity", "Char", "Perm"),
            ("AESER", "Serious Event", "Char", "Exp"),
            ("AEACN", "Action Taken with Study Treatment", "Char", "Exp"),
            ("AEREL", "Causality", "Char", "Exp"),
            ("AEOUT", "Outcome of Adverse Event", "Char", "Perm"),
            ("AESTDTC", "Start Date/Time of Adverse Event", "Char", "Exp"),
            ("AEENDTC", "End Date/Time of Adverse Event", "Char", "Exp"),
            ("AESTDY", "Study Day of Start of Adverse Event", "Num", "Perm"),
            ("AEENDY", "Study Day of End of Adverse Event", "Num", "Perm"),
        ],
    },
    "VS": {
        "label": "Vital Signs",
        "class": "Findings",
        "structure": "One record per vital sign measurement per time point per visit per subject",
        "variables": _IDENTIFIERS
        + [
            ("VSSEQ", "Sequence Number", "Num", "Req"),
            ("VSTESTCD", "Vital Signs Test Short Name", "Char", "Req"),
            ("VSTEST", "Vital Signs Test Name", "Char", "Req"),
            ("VSPOS", "Vital Signs Position of Subject", "Char", "Perm"),
            ("VSORRES", "Result or Finding in Original Units", "Char", "Exp"),
            ("VSORRESU", "Original Units", "Char", "Exp"),
            ("VSSTRESC", "Character Result/Finding in Std Format", "Char", "Exp"),
            ("VSSTRESN", "Numeric Result/Finding in Standard Units", "Num", "Exp"),
            ("VSSTRESU", "Standard Units", "Char", "Exp"),
            ("VSSTAT", "Completion Status", "Char", "Perm"),
            ("VSLOC", "Location of Vital Signs Measurement", "Char", "Perm"),
            ("VSLOBXFL", "Last Observation Before Exposure Flag", "Char", "Exp"),
        ]
        + _TIMING_VISIT
        + [
            ("VSDTC", "Date/Time of Measurements", "Char", "Exp"),
            ("VSDY", "Study Day of Vital Signs", "Num", "Perm"),
        ],
    },
    "LB": {
        "label": "Laboratory Test Results",
        "class": "Findings",
        "structure": "One record per lab test per time point per visit per subject",
        "variables": _IDENTIFIERS
        + [
            ("LBSEQ", "Sequence Number", "Num", "Req"),
            ("LBTESTCD", "Lab Test or Examination Short Name", "Char", "Req"),
            ("LBTEST", "Lab Test or Examination Name", "Char", "Req"),
            ("LBCAT", "Category for Lab Test", "Char", "Exp"),
            ("LBORRES", "Result or Finding in Original Units", "Char", "Exp"),
            ("LBORRESU", "Original Units", "Char", "Exp"),
            ("LBORNRLO", "Reference Range Lower Limit in Orig Unit", "Char", "Exp"),
            ("LBORNRHI", "Reference Range Upper Limit in Orig Unit", "Char", "Exp"),
            ("LBSTRESC", "Character Result/Finding in Std Format", "Char", "Exp"),
            ("LBSTRESN", "Numeric Result/Finding in Standard Units", "Num", "Exp"),
            ("LBSTRESU", "Standard Units", "Char", "Exp"),
            ("LBNRIND", "Reference Range Indicator", "Char", "Exp"),
            ("LBSPEC", "Specimen Type", "Char", "Perm"),
            ("LBLOBXFL", "Last Observation Before Exposure Flag", "Char", "Exp"),
        ]
        + _TIMING_VISIT
        + [
            ("LBDTC", "Date/Time of Specimen Collection", "Char", "Exp"),
            ("LBDY", "Study Day of Specimen Collection", "Num", "Perm"),
        ],
    },
    "CM": {
        "label": "Concomitant/Prior Medications",
        "class": "Interventions",
        "structure": "One record per recorded medication occurrence or constant-dosing interval per subject",
        "variables": _IDENTIFIERS
        + [
            ("CMSEQ", "Sequence Number", "Num", "Req"),
            ("CMTRT", "Reported Name of Drug, Med, or Therapy", "Char", "Req"),
            ("CMDECOD", "Standardized Medication Name", "Char", "Perm"),
            ("CMINDC", "Indication", "Char", "Perm"),
            ("CMDOSE", "Dose per Administration", "Num", "Perm"),
            ("CMDOSU", "Dose Units", "Char", "Perm"),
            ("CMDOSFRQ", "Dosing Frequency per Interval", "Char", "Perm"),
            ("CMROUTE", "Route of Administration", "Char", "Perm"),
            ("CMSTDTC", "Start Date/Time of Medication", "Char", "Perm"),
            ("CMENDTC", "End Date/Time of Medication", "Char", "Perm"),
        ],
    },
    "EX": {
        "label": "Exposure",
        "class": "Interventions",
        "structure": "One record per constant dosing interval per subject",
        "variables": _IDENTIFIERS
        + [
            ("EXSEQ", "Sequence Number", "Num", "Req"),
            ("EXTRT", "Name of Treatment", "Char", "Req"),
            ("EXDOSE", "Dose", "Num", "Exp"),
            ("EXDOSU", "Dose Units", "Char", "Exp"),
            ("EXDOSFRM", "Dose Form", "Char", "Exp"),
            ("EXDOSFRQ", "Dosing Frequency per Interval", "Char", "Perm"),
            ("EXROUTE", "Route of Administration", "Char", "Perm"),
            ("EXSTDTC", "Start Date/Time of Treatment", "Char", "Exp"),
            ("EXENDTC", "End Date/Time of Treatment", "Char", "Exp"),
        ],
    },
    "MH": {
        "label": "Medical History",
        "class": "Events",
        "structure": "One record per medical history event per subject",
        "variables": _IDENTIFIERS
        + [
            ("MHSEQ", "Sequence Number", "Num", "Req"),
            ("MHTERM", "Reported Term for the Medical History", "Char", "Req"),
            ("MHDECOD", "Dictionary-Derived Term", "Char", "Perm"),
            ("MHCAT", "Category for Medical History", "Char", "Perm"),
            ("MHBODSYS", "Body System or Organ Class", "Char", "Perm"),
            ("MHSTDTC", "Start Date/Time of Medical History Event", "Char", "Perm"),
            ("MHENDTC", "End Date/Time of Medical History Event", "Char", "Perm"),
        ],
    },
    "DS": {
        "label": "Disposition",
        "class": "Events",
        "structure": "One record per disposition status or protocol milestone per subject",
        "variables": _IDENTIFIERS
        + [
            ("DSSEQ", "Sequence Number", "Num", "Req"),
            ("DSTERM", "Reported Term for the Disposition Event", "Char", "Req"),
            ("DSDECOD", "Standardized Disposition Term", "Char", "Req"),
            ("DSCAT", "Category for Disposition Event", "Char", "Exp"),
            ("DSSTDTC", "Start Date/Time of Disposition Event", "Char", "Exp"),
        ],
    },
}

# Subset of CDISC controlled terminology, keyed by SDTM variable.
CONTROLLED_TERMINOLOGY: dict[str, list[str]] = {
    "SEX": ["F", "M", "U", "UNDIFFERENTIATED"],
    "AGEU": ["YEARS", "MONTHS", "WEEKS", "DAYS", "HOURS"],
    "ETHNIC": ["HISPANIC OR LATINO", "NOT HISPANIC OR LATINO", "NOT REPORTED", "UNKNOWN"],
    "RACE": [
        "AMERICAN INDIAN OR ALASKA NATIVE",
        "ASIAN",
        "BLACK OR AFRICAN AMERICAN",
        "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER",
        "WHITE",
        "MULTIPLE",
        "NOT REPORTED",
        "OTHER",
        "UNKNOWN",
    ],
    "AESEV": ["MILD", "MODERATE", "SEVERE"],
    "AESER": ["N", "Y"],
    "DTHFL": ["Y"],
    "AEOUT": [
        "FATAL",
        "NOT RECOVERED/NOT RESOLVED",
        "RECOVERED/RESOLVED",
        "RECOVERED/RESOLVED WITH SEQUELAE",
        "RECOVERING/RESOLVING",
        "UNKNOWN",
    ],
    "AEACN": [
        "DOSE INCREASED",
        "DOSE NOT CHANGED",
        "DOSE RATE REDUCED",
        "DOSE REDUCED",
        "DRUG INTERRUPTED",
        "DRUG WITHDRAWN",
        "NOT APPLICABLE",
        "UNKNOWN",
    ],
    "LBNRIND": ["ABNORMAL", "HIGH", "LOW", "NORMAL"],
    "VSTESTCD": ["DIABP", "HEIGHT", "PULSE", "RESP", "SYSBP", "TEMP", "WEIGHT", "BMI"],
    "VSPOS": ["SITTING", "STANDING", "SUPINE"],
}

# Raw-column keyword -> (SDTM domain, SDTM variable). Used for mapping suggestions.
COLUMN_SYNONYMS: dict[str, tuple[str, str]] = {
    "study": ("DM", "STUDYID"),
    "studyid": ("DM", "STUDYID"),
    "protocol": ("DM", "STUDYID"),
    "subject": ("DM", "SUBJID"),
    "subjid": ("DM", "SUBJID"),
    "patient": ("DM", "SUBJID"),
    "usubjid": ("DM", "USUBJID"),
    "site": ("DM", "SITEID"),
    "siteid": ("DM", "SITEID"),
    "sex": ("DM", "SEX"),
    "gender": ("DM", "SEX"),
    "dob": ("DM", "BRTHDTC"),
    "birth": ("DM", "BRTHDTC"),
    "age": ("DM", "AGE"),
    "race": ("DM", "RACE"),
    "ethnic": ("DM", "ETHNIC"),
    "ethnicity": ("DM", "ETHNIC"),
    "country": ("DM", "COUNTRY"),
    "arm": ("DM", "ARM"),
    "treatment_arm": ("DM", "ARM"),
    "consent": ("DM", "RFICDTC"),
    "death": ("DM", "DTHDTC"),
    "adverse": ("AE", "AETERM"),
    "ae_term": ("AE", "AETERM"),
    "aeterm": ("AE", "AETERM"),
    "event": ("AE", "AETERM"),
    "preferred_term": ("AE", "AEDECOD"),
    "pt": ("AE", "AEDECOD"),
    "soc": ("AE", "AESOC"),
    "severity": ("AE", "AESEV"),
    "serious": ("AE", "AESER"),
    "causality": ("AE", "AEREL"),
    "relationship": ("AE", "AEREL"),
    "outcome": ("AE", "AEOUT"),
    "onset": ("AE", "AESTDTC"),
    "resolution": ("AE", "AEENDTC"),
    "systolic": ("VS", "VSORRES"),
    "diastolic": ("VS", "VSORRES"),
    "pulse": ("VS", "VSORRES"),
    "heart_rate": ("VS", "VSORRES"),
    "temperature": ("VS", "VSORRES"),
    "weight": ("VS", "VSORRES"),
    "height": ("VS", "VSORRES"),
    "bmi": ("VS", "VSORRES"),
    "position": ("VS", "VSPOS"),
    "lab": ("LB", "LBTEST"),
    "analyte": ("LB", "LBTEST"),
    "test_code": ("LB", "LBTESTCD"),
    "specimen": ("LB", "LBSPEC"),
    "ref_low": ("LB", "LBORNRLO"),
    "ref_high": ("LB", "LBORNRHI"),
    "normal_low": ("LB", "LBORNRLO"),
    "normal_high": ("LB", "LBORNRHI"),
    "medication": ("CM", "CMTRT"),
    "drug": ("CM", "CMTRT"),
    "conmed": ("CM", "CMTRT"),
    "indication": ("CM", "CMINDC"),
    "route": ("CM", "CMROUTE"),
    "frequency": ("CM", "CMDOSFRQ"),
    "dose": ("EX", "EXDOSE"),
    "dose_unit": ("EX", "EXDOSU"),
    "dosing": ("EX", "EXDOSE"),
    "exposure": ("EX", "EXTRT"),
    "history": ("MH", "MHTERM"),
    "medical_history": ("MH", "MHTERM"),
    "disposition": ("DS", "DSTERM"),
    "discontinuation": ("DS", "DSDECOD"),
    "completion": ("DS", "DSDECOD"),
    "visit": ("VS", "VISIT"),
    "visitnum": ("VS", "VISITNUM"),
}
